name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman (CLI do Postman)
        run: npm install -g newman

      - name: Run Postman API Tests
        run: newman run postman_collection.json 

  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

  k6_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          wget https://github.com/grafana/k6/releases/download/v0.45.0/k6-v0.45.0-linux-amd64.tar.gz
          tar -xvzf k6-v0.45.0-linux-amd64.tar.gz
          sudo mv k6-v0.45.0-linux-amd64/k6 /usr/local/bin

      - name: Run k6 load test
        run: k6 run k6/load-test.js 
